import StreamController from "@components/stream-controller/stream-controller";
import type { Metadata, NextPage } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  themeColor: "#0C102E",
};

const FactoryComponent: NextPage = () => {
  return (
    <>Nothing</>

    // <StreamController />;
  );
};

export default FactoryComponent;
