import WagmiComponent from "@components/wagmiComponent/wagmi";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@components/footer/footer";
import Header from "@components/header/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  themeColor: "#0C102E",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WagmiComponent>
          <Header />
          {children}
          <Footer />
        </WagmiComponent>
      </body>
    </html>
  );
}
