import Footer from "@components/footer/footer";
import Header from "@components/header/header";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "BCSW",
  description: "Generated by create next app",
  themeColor: "#0C102E",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative bg-primary">
        {/* <WagmiComponent> */}
        {children}
        {/* </WagmiComponent> */}
      </body>
    </html>
  );
}
